language: csharp
solution: libwarcraft.sln
sudo: required
dist: trusty
dotnet: 2.0.0
before_install:
    - sudo add-apt-repository -y ppa:jarl-gullberg/blizzard-dev-tools
    - sudo apt-get update -q
script:
    - dotnet restore
    - dotnet build -c Release
