language: csharp
solution: libwarcraft.sln
sudo: required
dist: trusty
dotnet: 2.0.0
before_install:
    - sudo add-apt-repository -y ppa:jarl-gullberg/blizzard-dev-tools
    - sudo apt-get update -q
script:
    - dotnet add libwarcraft/libwarcraft.csproj package ImageSharp --version 1.0.0-alpha9-00194 --source "https://www.myget.org/F/imagesharp/api/v3/index.json;https://api.nuget.org/v3/index.json"
    - dotnet restore
    - dotnet build -c Release
